Adding SQLAlchemy and Alembic
zklevsha/todo-list pull request #10
Opened 2024-06-10 11:53 UTC by misa1313

2024-06-11 08:48 UTC, zklevsha requested changes

2024-06-11 08:48 UTC, zklevsha commented on db.py
> +    id = Column(Integer, primary_key=True, index=True)
Starting from SQLAlchemy 2.0 it`s recommended to use mapped_column function when declaring  da

```
from sqlalchemy.orm import declarative_base, mapped_column, Mapped
Base = declarative_base()

class User(Base):
    __tablename__ = 'users'
    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column()
```
**Links**

- [Discussion on StackOverFlow](https://stackoverflow.com/questions/76498857/what-is-the-difference-between-mapped-column-and-column-in-sqlalchemy)
- [SQLAlchemy2.0 documentation](https://docs.sqlalchemy.org/en/20/orm/quickstart.html)

2024-06-11 08:48 UTC, zklevsha commented on requirements.txt
>  fastapi==0.83.0
Bump sqlalchemy to 2.x.
1.4   "bugfix ony" status

2024-06-11 08:48 UTC, zklevsha commented on README.md
> +1.  **Initialize Alembic -** The below command will create a `migrations` directory with necessary configuration files:
You need to initialize alembic your self i.e. create migrations directory and autogenerate your migrations
This folder must be part of the project alongside with your code.
 
When deploying user just need to run `alembic upgrade head`

Here is some links for you about how to use Alembic: 
- [Hands-on artile on how to use alembic](url)
- [Alembic Tutorial](url)

2024-06-13 11:31 UTC, zklevsha requested changes

2024-06-13 11:31 UTC, zklevsha commented on db.py
>  engine = create_engine(connection_string)
Since we are using FastAPI which is asynchronous It`s better to use async engine 
```
engine = create_async_engine('postgresql+asyncpg://user:password@host:port/database')
```

2024-06-13 11:31 UTC, zklevsha commented on db.py
> +class Todos(Base):
It`s better to store SQLALchemy models in different module. 

Create `models.py` file and move `Base` and `Todos` classes there


Also you can move Pydantic schemas to the separate module as well: 
move `ConnectionResponse` and `BasicResponse` from `app.py` to `schemas.py`

2024-06-13 11:31 UTC, zklevsha commented on db.py
> +    with Session(engine) as session:
Common pattern is to use async_factory factory object that can be created via
Session = async_sessionmaker(engine)

Than use Session factory to create DB sessions in your code 
```
import Session from db

with Session() as session:
    session.add(some_object)
    session.add(some_other_object)
```

Main idea here is to set the same configurations for your Session in one place (`async_sessionmaker` function call)


**More info**
- [SQLALchemy documentaion](https://docs.sqlalchemy.org/en/20/orm/session_basics.html#using-a-sessionmaker)
- [Stackoverflow](https://stackoverflow.com/questions/15750557/sqlalchemy-why-create-a-sessionmaker-before-assign-it-to-a-session-object)

2024-06-13 11:31 UTC, zklevsha commented on db.py
>  def connect_test():
There is a convention that  states that db.py module should only have code regarding database connections i.e. `engine` and `sessison` objects

It\`s common practice  to place all functions for working with database in a separate module `crud.py`.
Create this file and move `connect_test`, `get_schema` functions there.
Also looks like `connect` function is not needed anymore (at least I did\`t found  where it`s used)


CRUD is an acronym that lists all the basic actions that can be performed via API : **c**reate, **r**ead, **u**pdate, **d**elete

2024-06-13 11:31 UTC, zklevsha commented on README.md
> +1.  **Configure Alembic -** Open `alembic.ini` and set your database URL:
You can set this dynamically  adding environment variables parsing logic to the 'migrations/env.py'  script. 


here  is snippet for reference

```
import os
from dotenv import load_dotenv

db = {'host': None, 'database': None, 'username': None, 'password': None}
for k in db.keys():
    val = os.environ.get(k)
    if not val:
        raise ValueError(f'enviroment variable {k} is not set')
    db[k] = val

sqlalchemy_url = f'postgresql+psycopg2://{db["username"]}:{db["password"]}@{db["host"]}/{db["database"]}'
config.set_main_option('sqlalchemy.url', sqlalchemy_url)

```

2024-07-08 08:07 UTC, zklevsha requested changes

2024-07-08 08:07 UTC, zklevsha commented on requirements.txt
> +psycopg2==2.9.9
I might be wrong but looks like we dont need `psycopg2` since we are using `asyncpg`
And we need `python-dotenv` to be here

2024-07-08 08:07 UTC, zklevsha commented on README.md
> +db_database=DATABASE
docker-compose.yml uses old  variable db_name. I guees you`ll need update it in the docker-compose.yml

2024-07-08 08:07 UTC, zklevsha commented on migrations/versions/30383fbd4ed1_creating_todos_table.py
> +    op.create_index(op.f('ix_todos_title'), 'todos', ['title'], unique=False)
I am a bit confused about this block
```  
op.create_index(op.f('ix_todos_description'), 'todos', ['description'], unique=False)
op.create_index(op.f('ix_todos_id'), 'todos', ['id'], unique=False)
op.create_index(op.f('ix_todos_title'), 'todos', ['title'], unique=False)
```
Did you added this manualy? Because I`ve Just tested your model on new alembic and got this migration (no index creation)
```
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
```
Usually Alembic will op.create_index only if you implicitly set this in your model
```
title: Mapped[str] = mapped_column(String(30), index=True)
```

There is no need for indexes on description and  title right now (especially for description)
and since id is Primary key postgres will create index for it automatically

I suggest for you to drop those indexes including ix_todos_id since postgres already have index for id called todos_pkey

```
    Column     |            Type             | Collation | Nullable |              Default              
---------------+-----------------------------+-----------+----------+-----------------------------------
 id            | integer                     |           | not null | nextval('todos_id_seq'::regclass)
 title         | character varying           |           |          | 
 description   | character varying           |           |          | 
 creation_date | timestamp without time zone |           |          | 
 is_finished   | boolean                     |           |          | 
Indexes:
    todos_pkey" PRIMARY KEY, btree (id)
    "ix_todos_description" btree (description)
    "ix_todos_id" btree (id)
    "ix_todos_title" btree (title)

```

2024-07-08 08:07 UTC, zklevsha commented on crud.py
> +async def get_schema():
Maybe it`ll be easier just use raw SQL (sqlalchemy allows it)

```
from sqlalchemy import text
async def get_schema():
    async with async_session() as session:
        query = text("SELECT version_num FROM alembic_version;")
        result = await session.execute(query)
        version_num = result.scalar()
        return version_num
```

2024-07-09 19:27 UTC, misa1313 commented on requirements.txt
> +psycopg2==2.9.9
Hi! "psycopg2" has been removed. "python-dotenv" was already in the file.

2024-07-09 19:29 UTC, misa1313 commented on migrations/versions/30383fbd4ed1_creating_todos_table.py
> +    op.create_index(op.f('ix_todos_title'), 'todos', ['title'], unique=False)
Indeed, the issue was that I auto-generated the file with the old version of SQLAlchemy and had the equivalent of "index=True" configured. This was corrected in the newer version, but the "30383fbd4ed1_creating_todos_table.py" file remained unchanged.

2024-07-09 19:29 UTC, misa1313 commented on crud.py
> +async def get_schema():
Much better, indeed!

2024-07-10 13:45 UTC, zklevsha approved these changes
Great job. 
Merging

2024-07-10 13:45 UTC, merged