Adding authentication and role-based access control
zklevsha/todo-list pull request #14
Opened 2024-08-29 01:22 UTC by misa1313

Addressing issue #13

2024-09-02 16:26 UTC, zklevsha requested changes

2024-09-02 16:26 UTC, zklevsha commented on oauth.py
> +oauth2_scheme = OAuth2PasswordBearer(tokenUrl='login')
tokenUrl should match yout login enpoin ('/api/v1/login')
Without it swagger ui cant authenticate you

2024-09-02 16:26 UTC, zklevsha commented on tasks_crud.py
> +from users_crud import handle_errors
handle_errors are used in two modules tasks_crud.py and users_crud.py
I think it`ll be better to move this function to separate helpers.py module

Also why not create folder/package crud and move tasks_crud and users_crud.py here
i.e.
```
├── crud
│   ├── __init__.py
│   ├── tasks.py
│   └── users.py

```

2024-09-02 16:26 UTC, zklevsha commented on settings.py
> +def generate_random_string(length):
move those functions to helpers.py or crypto.py module
no need to keep it in settings

2024-09-02 16:26 UTC, zklevsha commented on oauth.py
> +"""
There is deprecation warning I thing it`ll needs to be addressed
```
oauth.py:21: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
    expiration = datetime.utcnow() + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
```

2024-09-02 16:26 UTC, zklevsha commented on tests/test_tasks.py
> +from test_users import get_new_token
maybe it`ll be better to move get_new_token to tests/helpers.py

2024-09-02 16:26 UTC, zklevsha commented on tests/test_tasks.py
> +test_tasks.py
Maybe we also should test do admin related tasks 
```
Admins can modify or delete any tasks.
Only admins can create new admins.
```

2024-09-02 16:26 UTC, zklevsha commented on tests/test_users.py
> +async def log_user(test_client) -> None:
it`ll betere to rename function to login
log looks like logging related

2024-09-05 12:35 UTC, zklevsha requested changes

2024-09-05 12:35 UTC, zklevsha commented on README.md
> -`{"message":"This is another test route."}`
Remove `
this symbols cause red marks on code example

2024-09-05 12:35 UTC, zklevsha commented on crud/users.py
> +async def create_new_user(user: UserCreate, db: AsyncSession):
Currently, any user can register as an admin. We should allow users to register only as regular users. If needed, an admin can update a user's role and promote them to an admin.

2024-09-05 12:35 UTC, zklevsha commented on schemas.py
> +    creation_date: int = Field(default_factory=lambda: int(datetime.now().timestamp()))
User should not  set creation date. It should be set on backend itself
Same could aslo be done for Todos creation date

2024-09-05 12:47 UTC, zklevsha requested changes

2024-09-05 12:47 UTC, zklevsha commented on tests/test_users.py
> +"""
Add tests for /register endpoint
Dont forget to check that only admin can create new admin

2024-09-05 12:47 UTC, zklevsha commented on tests/test_users.py
> +async def test_delete_user(test_client) -> None:
check that admin can delete other users

2024-09-05 12:51 UTC, zklevsha requested changes

2024-09-05 12:51 UTC, zklevsha commented on crud/tasks.py
> +from crud.users import handle_errors
move hande_errors to crud.helpers

2024-09-05 14:57 UTC, misa1313 commented on README.md
> -`{"message":"This is another test route."}`
Hi! That seems to refer to an older version of the README file. The new one doesn't include that text.

2024-09-08 11:47 UTC, merged